// Package pairing holds the shared cryptographic primitives for the SAGE
// LAN node-join ceremony (Phase 5b-3), used by BOTH the host (web package) and
// the joining guest (sage-gui pair CLI / dashboard). Keeping it in one place
// guarantees the two sides derive identical proofs, SAS codes, and bundle
// encryption keys.
//
// Security model. A 32-byte secret S is generated by the host and delivered to
// the guest ONLY through the QR code / pairing token (a visual/out-of-band
// channel — the guest scans the host's screen). S never crosses the network:
//   - the guest proves possession of S with an HMAC (ProofHello / ProofBundle),
//   - both sides derive the 6-digit compare code (SAS) from S,
//   - the bundle (which contains the chain genesis — effectively the join
//     credential) is AES-256-GCM encrypted under a key derived from S, so a
//     network eavesdropper who never scanned the QR learns nothing usable.
// Each use of S is domain-separated by a distinct label so the subkeys are
// independent.
package pairing

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"fmt"
)

// SecretLen is the length of the pairing secret S in bytes.
const SecretLen = 32

// Domain-separation labels for the three uses of S.
const (
	labelProofHello  = "sage-pair/proof-hello"
	labelProofBundle = "sage-pair/proof-bundle"
	labelSAS         = "sage-pair/sas"
	labelEnc         = "sage-pair/enc-key"
)

// NewSecret returns a fresh cryptographically-random 32-byte pairing secret.
func NewSecret() ([]byte, error) {
	s := make([]byte, SecretLen)
	if _, err := rand.Read(s); err != nil {
		return nil, fmt.Errorf("generate pairing secret: %w", err)
	}
	return s, nil
}

// mac computes HMAC-SHA256(secret, label, parts...) with an INJECTIVE encoding:
// the label and each part are length-prefixed (8-byte big-endian) so no choice
// of part contents can produce the same byte stream as a different part
// sequence (a NUL separator alone would not, since a part may itself contain a
// NUL). Domain separation is by the distinct label.
func mac(secret []byte, label string, parts ...string) []byte {
	h := hmac.New(sha256.New, secret)
	writeLenPrefixed(h, []byte(label))
	for _, p := range parts {
		writeLenPrefixed(h, []byte(p))
	}
	return h.Sum(nil)
}

// writeLenPrefixed writes an 8-byte big-endian length followed by the bytes.
func writeLenPrefixed(h interface{ Write([]byte) (int, error) }, b []byte) {
	var lenbuf [8]byte
	binary.BigEndian.PutUint64(lenbuf[:], uint64(len(b)))
	_, _ = h.Write(lenbuf[:])
	_, _ = h.Write(b)
}

// ProofHello is the guest's proof it holds S, presented on first contact. It
// binds the session id, the guest's nonce, and the guest's node id.
func ProofHello(secret []byte, sessionID, guestNonce, guestNodeID string) string {
	return hex.EncodeToString(mac(secret, labelProofHello, sessionID, guestNonce, guestNodeID))
}

// ProofBundle is the guest's proof it holds S, presented when fetching the
// (already operator-approved) bundle.
func ProofBundle(secret []byte, sessionID string) string {
	return hex.EncodeToString(mac(secret, labelProofBundle, sessionID))
}

// VerifyProof constant-time compares an expected proof against a provided hex
// proof. A malformed provided value returns false.
func VerifyProof(expected, provided string) bool {
	e, err1 := hex.DecodeString(expected)
	p, err2 := hex.DecodeString(provided)
	if err1 != nil || err2 != nil {
		return false
	}
	return subtle.ConstantTimeCompare(e, p) == 1
}

// SAS derives the 6-digit short-authentication-string both operators compare.
func SAS(secret []byte, sessionID, guestNonce string) string {
	m := mac(secret, labelSAS, sessionID, guestNonce)
	n := binary.BigEndian.Uint32(m[:4]) % 1000000
	return fmt.Sprintf("%06d", n)
}

// EncryptBundle AES-256-GCM encrypts plaintext under a key derived from S.
// Returns base64 nonce and base64 ciphertext.
func EncryptBundle(secret, plaintext []byte) (nonceB64, ctB64 string, err error) {
	key := mac(secret, labelEnc) // 32 bytes → AES-256
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", "", err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return "", "", err
	}
	nonce := make([]byte, gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", "", err
	}
	ct := gcm.Seal(nil, nonce, plaintext, nil)
	return base64.StdEncoding.EncodeToString(nonce), base64.StdEncoding.EncodeToString(ct), nil
}

// DecryptBundle reverses EncryptBundle using S.
func DecryptBundle(secret []byte, nonceB64, ctB64 string) ([]byte, error) {
	nonce, err := base64.StdEncoding.DecodeString(nonceB64)
	if err != nil {
		return nil, fmt.Errorf("decode nonce: %w", err)
	}
	ct, err := base64.StdEncoding.DecodeString(ctB64)
	if err != nil {
		return nil, fmt.Errorf("decode ciphertext: %w", err)
	}
	key := mac(secret, labelEnc)
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, err
	}
	if len(nonce) != gcm.NonceSize() {
		return nil, fmt.Errorf("bad nonce length")
	}
	pt, err := gcm.Open(nil, nonce, ct, nil)
	if err != nil {
		return nil, fmt.Errorf("decrypt bundle (wrong secret or corrupt data): %w", err)
	}
	return pt, nil
}

// Token is the payload encoded into the QR / pairing code. It carries only what
// the guest needs to REACH the host and prove possession of S — never any part
// of the bundle.
type Token struct {
	Version   int    `json:"v"`
	Addr      string `json:"addr"` // host:port of the temporary LAN pairing listener
	SessionID string `json:"sid"`
	SecretB64 string `json:"s"` // base64(S)
}

// EncodeToken produces the compact base64url string shown as the QR / typed as
// the pairing code.
func EncodeToken(addr, sessionID string, secret []byte) (string, error) {
	t := Token{Version: 1, Addr: addr, SessionID: sessionID, SecretB64: base64.StdEncoding.EncodeToString(secret)}
	data, err := json.Marshal(t)
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(data), nil
}

// DecodeToken parses a pairing token and returns the fields plus the raw S.
func DecodeToken(token string) (Token, []byte, error) {
	data, err := base64.RawURLEncoding.DecodeString(token)
	if err != nil {
		return Token{}, nil, fmt.Errorf("decode token: %w", err)
	}
	var t Token
	if err := json.Unmarshal(data, &t); err != nil {
		return Token{}, nil, fmt.Errorf("parse token: %w", err)
	}
	if t.Version != 1 || t.Addr == "" || t.SessionID == "" {
		return Token{}, nil, fmt.Errorf("malformed pairing token")
	}
	secret, err := base64.StdEncoding.DecodeString(t.SecretB64)
	if err != nil || len(secret) != SecretLen {
		return Token{}, nil, fmt.Errorf("pairing token secret invalid")
	}
	return t, secret, nil
}
