package store

import (
	"context"
	"errors"
	"testing"

	badger "github.com/dgraph-io/badger/v4"
	"github.com/stretchr/testify/require"
)

func TestPublicMemoryStagePromotionRollbackAndCanonicalHooks(t *testing.T) {
	source := newTestBadger(t)
	seed := source.BeginConsensusTransaction(nil)
	publicTestRecord(t, seed, "one")
	publicTestRecord(t, seed, "two")
	require.NoError(t, seed.CommitConsensusTransaction())
	before, err := source.ComputeAppHashExcludingBookkeeping()
	require.NoError(t, err)
	legacyBefore, err := source.ComputeAppHash()
	require.NoError(t, err)
	v12Before, err := source.ComputeAppHashExcludingState()
	require.NoError(t, err)
	require.NoError(t, source.PreparePublicMemoryStage(context.Background(), 100))
	staged, err := source.ComputeAppHashExcludingBookkeeping()
	require.NoError(t, err)
	require.Equal(t, before, staged)
	legacyAfter, err := source.ComputeAppHash()
	require.NoError(t, err)
	v12After, err := source.ComputeAppHashExcludingState()
	require.NoError(t, err)
	require.Equal(t, legacyBefore, legacyAfter)
	require.Equal(t, v12Before, v12After)
	transaction := source.BeginConsensusTransaction(nil)
	require.Error(t, transaction.PromotePublicMemoryStage(101, before))
	require.Error(t, transaction.CommitConsensusTransaction())
	transaction.DiscardConsensusTransaction()
	_, err = source.PublicMemoryBranch("one")
	require.Error(t, err)
	transaction = source.BeginConsensusTransaction(nil)
	require.NoError(t, transaction.PromotePublicMemoryStage(100, before))
	require.NoError(t, transaction.SetMemoryStatusPreservingHash("one", "challenged"))
	require.NoError(t, transaction.SyncPublicMemoryChanges())
	require.NoError(t, transaction.CommitConsensusTransaction())
	require.NoError(t, source.ValidatePublicMemoryStage())
	proof, err := source.PublicMemoryBranch("one")
	require.NoError(t, err)
	require.Equal(t, "challenged", proof.Leaf.Status)
	other, err := source.PublicMemoryBranch("two")
	require.NoError(t, err)
	require.Equal(t, proof.Root, other.Root)
	transaction = source.BeginConsensusTransaction(nil)
	require.NoError(t, transaction.SetMemoryClassification("two", 1))
	require.NoError(t, transaction.SyncPublicMemoryChanges())
	require.NoError(t, transaction.CommitConsensusTransaction())
	_, err = source.PublicMemoryBranch("two")
	require.Error(t, err)
	_, err = source.PublicMemoryBranch("one")
	require.NoError(t, err)
	hash, err := source.ComputePublicMemoryAppHash()
	require.NoError(t, err)
	require.Len(t, hash, 32)
}

func TestPublicMemoryStageCorruptionAndPartialPromotionRefuse(t *testing.T) {
	source := newTestBadger(t)
	seed := source.BeginConsensusTransaction(nil)
	publicTestRecord(t, seed, "one")
	require.NoError(t, seed.CommitConsensusTransaction())
	before, err := source.ComputeAppHashExcludingBookkeeping()
	require.NoError(t, err)
	require.NoError(t, source.PreparePublicMemoryStage(context.Background(), 100))
	transaction := source.BeginConsensusTransaction(nil)
	attempts := 0
	transaction.writeFaultHook = func(int) error {
		attempts++
		if attempts == 2 {
			return errors.New("synthetic root-write failure")
		}
		return nil
	}
	require.Error(t, transaction.PromotePublicMemoryStage(100, before))
	require.Error(t, transaction.CommitConsensusTransaction())
	transaction.DiscardConsensusTransaction()
	require.Error(t, source.ValidatePublicMemoryStage())
	after, err := source.ComputeAppHashExcludingBookkeeping()
	require.NoError(t, err)
	require.Equal(t, before, after)
	transaction = source.BeginConsensusTransaction(nil)
	require.NoError(t, transaction.PromotePublicMemoryStage(100, before))
	require.NoError(t, transaction.CommitConsensusTransaction())
	require.NoError(t, source.db.Update(func(txn *badger.Txn) error {
		return txn.Delete(publicStageKey(publicNodeKey(publicPath("one"), 256)))
	}))
	require.Error(t, source.ValidatePublicMemoryStage())
}

func TestPublicMemoryStageRestartKeepsOverridesAndRejectsLostStage(t *testing.T) {
	directory := t.TempDir()
	source, err := NewBadgerStore(directory)
	require.NoError(t, err)
	seed := source.BeginConsensusTransaction(nil)
	publicTestRecord(t, seed, "one")
	publicTestRecord(t, seed, "two")
	require.NoError(t, seed.CommitConsensusTransaction())
	before, err := source.ComputeAppHashExcludingBookkeeping()
	require.NoError(t, err)
	require.NoError(t, source.PreparePublicMemoryStage(context.Background(), 100))
	transaction := source.BeginConsensusTransaction(nil)
	require.NoError(t, transaction.PromotePublicMemoryStage(100, before))
	require.NoError(t, transaction.SetMemoryStatusPreservingHash("one", "challenged"))
	require.NoError(t, transaction.SetMemoryClassification("two", 1))
	require.NoError(t, transaction.SyncPublicMemoryChanges())
	require.NoError(t, transaction.CommitConsensusTransaction())
	proof, err := source.PublicMemoryBranch("one")
	require.NoError(t, err)
	hash, err := source.ComputePublicMemoryAppHash()
	require.NoError(t, err)
	require.NoError(t, source.CloseBadger())
	source, err = NewBadgerStore(directory)
	require.NoError(t, err)
	defer source.CloseBadger()
	require.NoError(t, source.ValidatePublicMemoryStage())
	restarted, err := source.PublicMemoryBranch("one")
	require.NoError(t, err)
	require.Equal(t, proof, restarted)
	restartedHash, err := source.ComputePublicMemoryAppHash()
	require.NoError(t, err)
	require.Equal(t, hash, restartedHash)
	_, err = source.PublicMemoryBranch("two")
	require.Error(t, err)
	require.NoError(t, source.db.DropPrefix(publicStagePrefix))
	require.Error(t, source.ValidatePublicMemoryStage())
	require.Error(t, source.PreparePublicMemoryStage(context.Background(), 101))
}

func TestPublicMemoryStageWrongSourceHashPoisonsPromotion(t *testing.T) {
	source := newTestBadger(t)
	seed := source.BeginConsensusTransaction(nil)
	publicTestRecord(t, seed, "one")
	require.NoError(t, seed.CommitConsensusTransaction())
	before, err := source.ComputeAppHashExcludingBookkeeping()
	require.NoError(t, err)
	require.NoError(t, source.PreparePublicMemoryStage(context.Background(), 100))
	wrong := append([]byte(nil), before...)
	wrong[0] ^= 1
	transaction := source.BeginConsensusTransaction(nil)
	require.NoError(t, transaction.SetMemoryStatusPreservingHash("one", "challenged"))
	require.Error(t, transaction.PromotePublicMemoryStage(100, wrong))
	require.Error(t, transaction.ConsensusTransactionError())
	require.Error(t, transaction.CommitConsensusTransaction())
	transaction.DiscardConsensusTransaction()
	state, err := source.GetMemoryDisclosureState("one")
	require.NoError(t, err)
	require.Equal(t, "committed", state.Status)
	after, err := source.ComputeAppHashExcludingBookkeeping()
	require.NoError(t, err)
	require.Equal(t, before, after)
}
